[build]
builder = "NIXPACKS"

[build.config]
# Specify Java version for Nixpacks (optional, but good practice)
# Nixpacks usually detects Java, but specifying ensures version 17
# Check Nixpacks documentation for exact provider keys if needed
# Example using common Nixpacks structure:
# nixpkgs = ["jdk17"]
# Or using providers:
providers = ["java"]

[deploy]
# Default start command for Spring Boot JAR built by Maven
# Nixpacks usually figures this out, but specifying can help
# The exact JAR name might vary slightly based on version, use wildcard
startCommand = "java -jar target/railway-postgres-app-maven-*.jar"
# Ensure health check points to a valid endpoint (root or actuator/health if added)
# healthcheckPath = "/actuator/health"
# healthcheckTimeout = 120

